security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        db_provider:
            entity:
                class: AppBundle:User
        hwi:
            id: user.social_oauth_user_provider
    firewalls:
        secured_area:
            anonymous: ~
            logout:
                path:   /user/logout
                success_handler: user.listener.logout
                invalidate_session: false
                target: /
            oauth:
                resource_owners:
                    facebook:          "/login/check-facebook"
                login_path:        /user/login
                use_forward:       false
                failure_path:      /user/login
                default_target_path: /
                oauth_user_provider:
                    service: user.social_oauth_user_provider
            guard:
                authenticators:
                    - user.security.authentication.login_form
                entry_point: user.security.authentication.login_form

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
